config/routes.rb
Rails.application.routes.draw do

  resources :carts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pedido/:id', to: 'order#show', as: 'order'
  post 'pedido/:cart_id', to: "order#create", as: "orders_create"
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  accepts_nested_attributes_for :cart_items, reject_if: proc { |attributes| attributes['genre'].blank? }

  def total
    cart_items.inject(0) {|sum, item| sum + (item.price * item.quantity)}
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :price, :item_type, presence: true
  scope :foods, -> {where(item_type: "food")}
  scope :drinks, -> {where(item_type: "drink")}
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  validates :price, :name, :quantity, :item_type, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  CONSTANT_NUMBER = 1782
  CONSTANT_FACTOR = 17
  after_create :initialize_order
  validates :table, presence: true
  has_many :line_items

  def initialize_order
    update_attributes(:number => (id * CONSTANT_FACTOR) + CONSTANT_NUMBER)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def new
    @items = Item
    @cart = Cart.new
  end

  def show
    set_cart
  end

  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if CartManager.new(@cart).perform
        format.html { redirect_to @cart }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_cart
    @cart = Cart.find(params[:id])
  end
  def cart_params
    params.require(:cart).permit(:table,cart_items_attributes: [:genre, :quantity])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def create
    @cart = Cart.find(params[:cart_id])
    @order = OrderManager.new(@cart).perform
    redirect_to @order
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/new.html.erb
<h1>Faça seu pedido</h1>
<div id="left">
  <h4>Comidas</h4>
  <ul>
    <% @items.foods.all.each do |food| %>
      <li>
        <%= food.name %> | <%= number_to_currency food.price %>
      </li>
    <% end %>
  </ul>
</div>
<div id="right">
  <h4>Bebidas</h4>
  <ul>
    <% @items.drinks.all.each do |drink| %>
      <li>
        <%= drink.name %> | <%= number_to_currency drink.price %>
      </li>
    <% end %>
  </ul>
</div>
<br />
<div class="clear"></div>
<div class="cart_form">
  <%= nested_form_for @cart do |f|%>
    <%= f.label "Mesa" %>
    <%= f.select :table, options_for_select((1..45).to_a, 1) %>
    <br />
    <%= f.fields_for :cart_items do |ff| %>
      <div>
        <%= ff.label "Tipo" %>
        <%= ff.select :genre, options_from_collection_for_select(@items.all, :id, :name) %>
      </div>
      <div>
        <%= ff.label "Quantidade" %>
        <%= ff.select :quantity, options_for_select((1..6).to_a, 1) %>
      </div>
        <%= ff.link_to_remove "Remover esse item" %>
    <% end %>
    <%= f.link_to_add "Adicionar item", :cart_items %>
    <%= f.button :submit%>
  <% end %>
</div>

app/views/carts/show.html.erb
<h1>Confirme seu pedido</h1>
<br />
<h4>Mesa</h4>
<p><%= @cart.table %>
</p>
<ul>
  <% @cart.cart_items.each do |item| %>
    <li>
      <%= item.name %>
      <%= item.quantity %>
    </li>
  <% end %>
</ul>

<div id='total'>
  <h4>Total</h4>
  <%= @cart.total %>
</div>

<%= link_to "Finalizar pedido", orders_create_path(@cart), method: "POST" %>

app/views/home/index.html.erb
<h1>Bem vindo ao Krusty Burger 2!! </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="page-header">
      <div class="navbar-inner">
        <div class="container">
          <h1>
            <%= link_to "Krusty Burger", root_path, id: "logo" %>
          </h1>
          <ul class="nav nav-tabs pull-right">
            <li><%= link_to "Criar pedido", new_cart_path %></li>
          </ul>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %></body>
</html>

app/views/order/show.html.erb
<h1>Seu pedido está sendo feito!</h1>
<p>Atualize a página para ver o andamento do seu pedido</p>
<%= @order.state %>